import type {
  User,
  Workout,
  Run,
  Quest,
  Achievement,
  DashboardStats,
} from "./types";

export const mockUser: User = {
  name: "Sid",
  avatar: "⚔️",
  level: 12,
  xp: 2450,
  xpToNextLevel: 3000,
  streak: 14,
  totalWorkouts: 87,
  totalDistance: 142.5,
  joinDate: "2025-01-15",
};

export const mockWorkouts: readonly Workout[] = [
  {
    id: "w1",
    type: "strength",
    title: "Upper Body Power",
    exercises: [
      { name: "Bench Press", sets: 4, reps: 8, weight: 80 },
      { name: "Overhead Press", sets: 3, reps: 10, weight: 40 },
      { name: "Barbell Row", sets: 4, reps: 8, weight: 70 },
      { name: "Dumbbell Curl", sets: 3, reps: 12, weight: 14 },
    ],
    duration: 65,
    xpEarned: 150,
    date: "2026-05-14",
  },
  {
    id: "w2",
    type: "hiit",
    title: "HIIT Circuit Burn",
    exercises: [
      { name: "Burpees", sets: 4, reps: 15, weight: null },
      { name: "Kettlebell Swings", sets: 4, reps: 20, weight: 16 },
      { name: "Box Jumps", sets: 3, reps: 12, weight: null },
      { name: "Mountain Climbers", sets: 3, reps: 30, weight: null },
    ],
    duration: 35,
    xpEarned: 200,
    date: "2026-05-13",
  },
  {
    id: "w3",
    type: "strength",
    title: "Leg Day Destroyer",
    exercises: [
      { name: "Squat", sets: 5, reps: 5, weight: 100 },
      { name: "Romanian Deadlift", sets: 4, reps: 8, weight: 80 },
      { name: "Leg Press", sets: 3, reps: 12, weight: 150 },
      { name: "Calf Raises", sets: 4, reps: 15, weight: 60 },
    ],
    duration: 70,
    xpEarned: 175,
    date: "2026-05-12",
  },
  {
    id: "w4",
    type: "cardio",
    title: "Rowing Endurance",
    exercises: [
      { name: "Rowing Machine", sets: 1, reps: 1, weight: null },
      { name: "Jump Rope", sets: 5, reps: 100, weight: null },
    ],
    duration: 40,
    xpEarned: 120,
    date: "2026-05-10",
  },
  {
    id: "w5",
    type: "flexibility",
    title: "Recovery & Mobility",
    exercises: [
      { name: "Foam Rolling", sets: 1, reps: 1, weight: null },
      { name: "Hip Flexor Stretch", sets: 3, reps: 1, weight: null },
      { name: "Shoulder Dislocates", sets: 3, reps: 15, weight: null },
    ],
    duration: 30,
    xpEarned: 75,
    date: "2026-05-09",
  },
];

export const mockRuns: readonly Run[] = [
  {
    id: "r1",
    distance: 5.2,
    duration: 28,
    pace: 5.38,
    difficulty: "moderate",
    xpEarned: 130,
    date: "2026-05-14",
  },
  {
    id: "r2",
    distance: 10.0,
    duration: 52,
    pace: 5.2,
    difficulty: "hard",
    xpEarned: 250,
    date: "2026-05-12",
  },
  {
    id: "r3",
    distance: 3.0,
    duration: 18,
    pace: 6.0,
    difficulty: "easy",
    xpEarned: 80,
    date: "2026-05-11",
  },
  {
    id: "r4",
    distance: 7.5,
    duration: 38,
    pace: 5.07,
    difficulty: "hard",
    xpEarned: 200,
    date: "2026-05-08",
  },
  {
    id: "r5",
    distance: 2.0,
    duration: 14,
    pace: 7.0,
    difficulty: "easy",
    xpEarned: 50,
    date: "2026-05-06",
  },
];

export const mockQuests: readonly Quest[] = [
  // Daily quests
  {
    id: "q1",
    title: "Morning Warrior",
    description: "Complete a workout before 9 AM",
    category: "daily",
    xpReward: 50,
    progress: 1,
    total: 1,
    completed: true,
    icon: "🌅",
  },
  {
    id: "q2",
    title: "Iron Pumper",
    description: "Log a strength workout today",
    category: "daily",
    xpReward: 75,
    progress: 0,
    total: 1,
    completed: false,
    icon: "💪",
  },
  {
    id: "q3",
    title: "Road Runner",
    description: "Run at least 3 km today",
    category: "daily",
    xpReward: 60,
    progress: 2.1,
    total: 3,
    completed: false,
    icon: "🏃",
  },
  // Weekly quests
  {
    id: "q4",
    title: "Workout Warrior",
    description: "Complete 5 workouts this week",
    category: "weekly",
    xpReward: 300,
    progress: 3,
    total: 5,
    completed: false,
    icon: "⚔️",
  },
  {
    id: "q5",
    title: "Marathon Prep",
    description: "Run a total of 20 km this week",
    category: "weekly",
    xpReward: 400,
    progress: 15.2,
    total: 20,
    completed: false,
    icon: "🏅",
  },
  {
    id: "q6",
    title: "Variety Pack",
    description: "Do 3 different workout types this week",
    category: "weekly",
    xpReward: 250,
    progress: 2,
    total: 3,
    completed: false,
    icon: "🎯",
  },
  // Special quests
  {
    id: "q7",
    title: "Century Club",
    description: "Reach 100 total workouts",
    category: "special",
    xpReward: 1000,
    progress: 87,
    total: 100,
    completed: false,
    icon: "🏆",
  },
  {
    id: "q8",
    title: "Streak Legend",
    description: "Maintain a 30-day streak",
    category: "special",
    xpReward: 750,
    progress: 14,
    total: 30,
    completed: false,
    icon: "🔥",
  },
];

export const mockAchievements: readonly Achievement[] = [
  {
    id: "a1",
    title: "First Steps",
    description: "Complete your first workout",
    icon: "👟",
    rarity: "common",
    unlocked: true,
    unlockedDate: "2025-01-15",
  },
  {
    id: "a2",
    title: "Getting Strong",
    description: "Bench press your body weight",
    icon: "🏋️",
    rarity: "rare",
    unlocked: true,
    unlockedDate: "2025-04-20",
  },
  {
    id: "a3",
    title: "Speed Demon",
    description: "Run 5 km under 25 minutes",
    icon: "⚡",
    rarity: "rare",
    unlocked: true,
    unlockedDate: "2025-08-12",
  },
  {
    id: "a4",
    title: "Iron Will",
    description: "Complete 50 strength workouts",
    icon: "🛡️",
    rarity: "epic",
    unlocked: true,
    unlockedDate: "2026-02-10",
  },
  {
    id: "a5",
    title: "Unstoppable",
    description: "Maintain a 30-day streak",
    icon: "🔥",
    rarity: "epic",
    unlocked: false,
  },
  {
    id: "a6",
    title: "Legendary Warrior",
    description: "Reach level 25",
    icon: "👑",
    rarity: "legendary",
    unlocked: false,
  },
];

export const mockDashboardStats: DashboardStats = {
  weeklyWorkouts: 4,
  weeklyDistance: 18.2,
  totalAchievements: 4,
  lifetimeXP: 12450,
};
